services:
  - type: web
    name: shopkart
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn shoeskart.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.4
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        sync: false
