# Generated by Django 5.0.4 on 2024-05-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_products_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='user_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
